version: '3.4'

services:
  uthgard.herald:
    image: uthgardherald:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_uthgard.herald$
    volumes:
      - D:\git\privat\herald\Uthgard.Herald\Uthgard.Herald:/app
      - C:\Users\Tobias\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_uthgard.herald$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_uthgard.herald$ bin/Debug/netcoreapp2.0/Uthgard.Herald.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
